# Generated by Django 5.1.1 on 2025-01-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_buy_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='buy_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
