# Generated by Django 5.1.1 on 2024-12-24 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20241224_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Green', 'Green'), ('Yellow', 'Yellow')], default='Black', max_length=20),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=3),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='products.category'),
        ),
    ]
