# Generated by Django 5.1.1 on 2024-12-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_product_review_clothing_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='comment',
        ),
    ]
