# Generated by Django 5.1.1 on 2024-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(upload_to='products/clothing_images/'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
