# Generated by Django 5.1.1 on 2024-12-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_clothingitem_image_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=100, unique=True),
        ),
    ]
